# Generated by Django 4.0 on 2023-07-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('patient_number', models.CharField(max_length=100, unique=True, verbose_name='ID пользователя в Лотусе')),
                ('name_last', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('name_first', models.CharField(max_length=256, verbose_name='Имя')),
                ('name_middle', models.CharField(max_length=256, verbose_name='Отчество')),
                ('sex', models.CharField(max_length=20, verbose_name='Пол')),
                ('bday', models.DateField(verbose_name='Дата рождения')),
                ('doc_name', models.CharField(max_length=256, verbose_name='На основе какого документа')),
                ('doc_series', models.CharField(max_length=64, verbose_name='Серия')),
                ('doc_number', models.CharField(max_length=128, verbose_name='Номер')),
                ('doc_agancy', models.CharField(max_length=256, verbose_name='Кем выдан')),
                ('doc_date', models.DateField(verbose_name='Дата выдачи')),
                ('address', models.CharField(max_length=1024, verbose_name='Адрес')),
                ('phone1', models.CharField(max_length=36, verbose_name='Номер телефона 1')),
                ('phone2', models.CharField(max_length=36, verbose_name='Номер телефона 1')),
                ('email', models.CharField(max_length=128, verbose_name='Электронаня почта')),
                ('polis', models.CharField(max_length=512, verbose_name='Полис')),
                ('policlinika', models.CharField(max_length=32, verbose_name='Номер поликлиники в системе')),
                ('isFizikPerson', models.BooleanField(verbose_name='Физ. лицо?')),
                ('dog1', models.BooleanField(verbose_name='договор 1')),
                ('dog2', models.BooleanField(verbose_name='договор 2')),
                ('isAmb', models.BooleanField(verbose_name='Амбулаторный?')),
                ('dms_num', models.CharField(max_length=512, verbose_name='ДМС номер')),
                ('dms_org', models.CharField(max_length=512, verbose_name='ДМС организация')),
                ('dms_inn', models.CharField(max_length=512, verbose_name='ДМС инн')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
