# Generated by Django 4.0 on 2023-07-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bday',
            field=models.CharField(max_length=20, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='doc_date',
            field=models.CharField(max_length=20, verbose_name='Дата выдачи'),
        ),
    ]
